spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    ddl-auto: create-drop
    defer-datasource-initialization: true

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      expire-length: 3600000
